version: "3"
services:
  serval:
    hostname: serval
    container_name: serval_cntr
    build:
      context: .
      dockerfile: dockerfile.development
    environment:
      - ASPNETCORE_Kestrel__Endpoints__Http__Url=http://*:80
      - ASPNETCORE_Kestrel__Endpoints__Http2__Url=http://*:81
      - ASPNETCORE_Kestrel__Endpoints__Http2__Protocols=Http2
      - ASPNETCORE_ConnectionStrings__Hangfire=mongodb://mongo:27017/serval_jobs?replicaSet=myRS
      - ASPNETCORE_ConnectionStrings__Mongo=mongodb://mongo:27017/serval?replicaSet=myRS
      - ASPNETCORE_Auth__Domain=sil-appbuilder.auth0.com
      - ASPNETCORE_Auth__Audience=https://machine.sil.org
      - ASPNETCORE_Logging__LogLevel__Default=Information
      - ASPNETCORE_Logging__LogLevel__Microsoft.AspNetCore=Warning
      - ASPNETCORE_Translation__Engines__0__Type=Echo
      - ASPNETCORE_Translation__Engines__0__Address=http://echo
      - ASPNETCORE_Translation__Engines__1__Type=SmtTransfer
      - ASPNETCORE_Translation__Engines__1__Address=http://machine-server
    expose:
      - 80
      - 81
    ports:
      - 80:80
    depends_on:
      - mongo
    volumes:
      - .:/app:ro
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - /var/lib/serval/serval:/var/lib/serval
    working_dir: '/app/src/Serval.ApiServer'
    entrypoint:
      - dotnet
      - run
      - --no-build
      - --no-launch-profile
      - --additionalProbingPath
      - /root/.nuget/packages

  echo:
    hostname: echo
    container_name: echo_cntr
    build:
      context: .
      dockerfile: dockerfile.development
    environment:
      - ASPNETCORE_Kestrel__Endpoints__Http__Url=http://*:80
      - ASPNETCORE_Kestrel__EndpointDefaults__Protocols=Http2
      - ASPNETCORE_Logging__LogLevel__Default=Information
      - ASPNETCORE_Logging__LogLevel__Microsoft.AspNetCore=Warning
      - ASPNETCORE_ConnectionStrings__TranslationPlatformApi=http://serval:81
    expose:
      - 80
    ports:
      - 81:80
    depends_on:
      - serval
    volumes:
      - .:/app:ro
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - /var/lib/serval/echo:/var/lib/serval
    working_dir: '/app/samples/EchoTranslationEngine'
    entrypoint:
      - dotnet
      - run
      - --no-build
      - --no-launch-profile
      - --additionalProbingPath
      - /root/.nuget/packages

  machine-server:
    hostname: machine-server
    container_name: machine-server-cntr
    build:
      context: ../machine
      dockerfile: ../machine/dockerfile.development

    environment:
      - ASPNETCORE_Kestrel__Endpoints__Https__Url=http://*:80
      - ASPNETCORE_Kestrel__EndpointDefaults__Protocols=Http2
      - ASPNETCORE_ConnectionStrings__Hangfire=mongodb://mongo:27017/machine_jobs?replicaSet=myRS
      - ASPNETCORE_ConnectionStrings__Mongo=mongodb://mongo:27017/machine?replicaSet=myRS
      - ASPNETCORE_ConnectionStrings__Serval=http://serval:81
      - ASPNETCORE_Logging__LogLevel__Default=Information
      - ASPNETCORE_Logging__LogLevel__Microsoft.AspNetCore=Warning
      - ASPNETCORE_TranslationEngines__0=SmtTransfer
    expose:
      - 80
    ports:
      - 82:80
    depends_on:
      - mongo
      - serval
    volumes:
      - ../machine:/app:ro
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - /var/lib/serval/engine_server:/var/lib/machine
    working_dir: '/app/src/SIL.Machine.WebApi.EngineServer'
    entrypoint:
      - dotnet
      - run
      - --no-build
      - --no-launch-profile
      - --additionalProbingPath
      - /root/.nuget/packages

  machine-job-server:
    hostname: machine-job-server
    container_name: machine-job-cntr
    build:
      context: ../machine
      dockerfile: ../machine/dockerfile.development
    environment:
      - ASPNETCORE_ConnectionStrings__Hangfire=mongodb://mongo:27017/machine_jobs?replicaSet=myRS
      - ASPNETCORE_ConnectionStrings__Mongo=mongodb://mongo:27017/machine?replicaSet=myRS
      - ASPNETCORE_ConnectionStrings__Serval=http://serval:81
      - ASPNETCORE_Logging__LogLevel__Default=Information
      - ASPNETCORE_Logging__LogLevel__Microsoft.AspNetCore=Warning
      - ASPNETCORE_Kestrel__Endpoints__Http__Url=http://*:80
      - ASPNETCORE_Kestrel__EndpointDefaults__Protocols=Http2
      - ASPNETCORE_TranslationEngines__0=SmtTransfer
    expose:
      - 80
    ports:
      - 83:80
    depends_on:
      - mongo
      - machine-server
    volumes:
      - ../machine:/app:ro
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - /var/lib/serval/engine_server:/var/lib/machine
    working_dir: '/app/src/SIL.Machine.WebApi.JobServer'
    entrypoint:
      - dotnet
      - run
      - --no-build
      - --no-launch-profile
      - --additionalProbingPath
      - /root/.nuget/packages
  mongo:
    hostname: mongo
    image: mongo:4.2
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    command: mongod --replSet myRS

  # this initialization server runs the `rs.initiate` command to
  # intialize the replica set and could connect the (1) servers to each other
  mongoinit:
    image: mongo:4.2
    # this container will exit after executing the command
    restart: "no"
    depends_on:
      - mongo
    command: >
      mongo --host mongo:27017 --eval ' config = { "_id" : "myRS", "members" : [
        {
          "_id" : 0,
          "host" : "mongo:27017"
        }
      ] }; sleep(3000); rs.initiate(config, { force: true }); '
