FROM mcr.microsoft.com/dotnet/sdk:8.0-jammy
RUN apt update && apt install unzip && \
    curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l /remote_debugger
RUN dotnet tool install --global dotnet-counters
ENV PATH="${PATH}:~/.dotnet/tools"