version: "3"
services:
  mongo:
    hostname: mongo
    image: mongo:8.0
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    # Run Mongo (with output to normal shell)
    # then configure the locally running mongo to be a standalone replica set
    # then hang forever so the container does not exit
    command:
      [
        '/bin/sh',
        '-c',
        'mongod --profile=2 --replSet myRS --bind_ip 0.0.0.0 & sleep 2s; mongosh --host localhost:27017 --eval '' config = { "_id" : "myRS", "members" : [{"_id" : 0,"host" : "mongo:27017"}] }; rs.initiate(config, { force: true }); '' ; sleep infinity'
      ]
