{{- if not .Values.localVolume}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: machine-mongo-claim
  namespace: {{ .Values.namespace}}
spec:
  storageClassName: "longhorn"
  accessModes:
      - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
{{- end }}