apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: {{ .Values.namespace }}-loki-output
  namespace: {{ .Values.namespace }}
spec:
  loki:
    buffer:
      flush_interval: 10s
      flush_mode: interval
    configure_kubernetes_labels: true
    tenant: {{ .Values.lokiTenent }}
    url: {{ .Values.lokiUrl }}
status:
  active: true
