apiVersion: v1
kind: Service
metadata:
  labels:
    app: machine-job
  name: machine-job
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: machine-job
status:
  loadBalancer: {}
