apiVersion: v1
kind: Service
metadata:
  labels:
    app: machine-engine
  name: machine-engine
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: machine-engine
status:
  loadBalancer: {}
