apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: serval-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  ingressClassName: nginx
  {{- if .Values.enableTls }}
  tls:
    - hosts:
        - {{.Values.externalHost}}
  #    secretName: testsecret-tls
  {{- end }}
  rules:
    - host: {{.Values.externalHost}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: serval-api
                port:
                  number: 80
            # hide metrics and health endpoints
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: default-http-backend
                port:
                  number: 80
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: default-http-backend
                port:
                  number: 81
