apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: serval-api-monitor
  namespace: {{ .Values.namespace }}
spec:
  endpoints:
    - port: http
      path: /metrics
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  selector:
    matchLabels:
      app: serval-api