apiVersion: v1
kind: Service
metadata:
  labels:
    app: serval-api
  name: serval-api
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: "81"
      port: 81
      targetPort: 81
  selector:
    app: serval-api
status:
  loadBalancer: {}
