apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: serval-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.namespace }}-maxrequestbody-limit@kubernetescrd,{{ .Values.namespace }}-redirectmetrics@kubernetescrd
spec:
  ingressClassName: traefik
  {{- if .Values.enableTls }}
  tls:
    - hosts:
        - {{.Values.externalHost}}
      {{- if eq .Values.namespace "nlp"}}
      secretName: qa-int-serval-api-tls
      {{- end}}
  {{- end }}
  rules:
    - host: {{.Values.externalHost}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: serval-api
                port:
                  number: 80
