apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: machine-job
  name: machine-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: machine-job
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: machine-job
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - command:
            - dotnet
            - /app/job_server/SIL.Machine.WebApi.JobServer.dll
          workingDir: /app/job_server
          env:
            - name: ASPNETCORE_Kestrel__Endpoints__Grpc__Url
              value: http://*:80
            - name: ASPNETCORE_Kestrel__Endpoints__Grpc__Protocols
              value: Http2
            - name: ASPNETCORE_ConnectionStrings__Hangfire
              value: mongodb://mongo:27017/machine_jobs
            - name: ASPNETCORE_ConnectionStrings__Mongo
              value: mongodb://mongo:27017/machine
            - name: ASPNETCORE_ConnectionStrings__Serval
              value: http://serval:81
            - name: ASPNETCORE_Logging__LogLevel__Default
              value: Information
            - name: ASPNETCORE_Logging__LogLevel__Microsoft.AspNetCore
              value: Warning
            - name: ASPNETCORE_TranslationEngines__0
              value: SmtTransfer
              {{- if not .Values.localVolume}}
              {{- template "secrets.clearml" }}
              {{- template "secrets.s3" }}
              {{- end}}
          image: {{ .Values.machineImage}}
          imagePullPolicy: "Always"
          name: machine-job
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "1000Mi"
              cpu: "1.5"
            requests:
              memory: "100Mi"
              cpu: "100m"
          volumeMounts:
            - mountPath: /var/lib/machine
              name: machine-mount
      hostname: machine-job
      restartPolicy: Always
      {{- if .Values.localVolume }}
      volumes:
        - hostPath:
            path: /host/engines #/host should be mounted from C:\usr\local
          name: machine-mount
      {{- else}}
      volumes:
        - name: machine-mount
          persistentVolumeClaim:
            claimName: machine-claim
      {{- end}}
status: {}
