apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: machine-engine
  name: machine-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: machine-engine
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: machine-engine
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - command:
            - dotnet
            - /app/engine_server/SIL.Machine.Serval.EngineServer.dll
          workingDir: /app/engine_server
          env:
            - name: ASPNETCORE_Kestrel__Endpoints__Grpc__Url
              value: http://*:80
            - name: ASPNETCORE_Kestrel__Endpoints__Grpc__Protocols
              value: Http2
            - name: ASPNETCORE_ConnectionStrings__Hangfire
              value: mongodb://mongo:27017/machine_jobs?replicaSet=myRS
            - name: ASPNETCORE_ConnectionStrings__Mongo
              value: mongodb://mongo:27017/machine?replicaSet=myRS
            - name: ASPNETCORE_ConnectionStrings__Serval
              value: http://serval-api:81
            - name: ASPNETCORE_Logging__LogLevel__Default
              value: Information
            - name: ASPNETCORE_Logging__LogLevel__Microsoft.AspNetCore
              value: Warning
            - name: ASPNETCORE_TranslationEngines__0
              value: SmtTransfer
            - name: ASPNETCORE_TranslationEngines__1
              value: Nmt
              {{- template "secrets.clearml" }}
              {{- template "secrets.s3" }}
          image: {{ .Values.machineImage}}
          imagePullPolicy: "Always"
          name: machine-engine
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
            requests:
              memory: "100Mi"
              cpu: "100m"
          volumeMounts:
            - mountPath: /var/lib/machine
              name: machine-mount
            - mountPath: /var/lib/serval
              name: serval-mount
              readOnly: true
            - mountPath: /root/.aspnet/DataProtection-Keys
              name: server-keys
      hostname: machine-engine
      restartPolicy: Always
      {{- if .Values.localVolume }}
      volumes:
        - hostPath:
            path: /host/engines #/host should be mounted from C:\usr\local
          name: machine-mount
        - hostPath:
            path: /host/serval
          name: serval-mount
        - hostPath:
            path: /host/DataProtection-Keys
          name: server-keys
      {{- else}}
      volumes:
        - name: machine-mount
          persistentVolumeClaim:
            claimName: machine-claim
        - name: serval-mount
          persistentVolumeClaim:
            claimName: serval-claim
        - name: server-keys
          persistentVolumeClaim:
            claimName: keys-claim
      {{- end}}
status: {}
