apiVersion: v1
kind: Pod
metadata:
  annotations:
  creationTimestamp: null
  labels:
    io.kompose.service: mongoinit
  name: mongoinit
spec:
  containers:
    - name: mongoinit
      image: mongo:4.2
      args:
        - mongo
        - --host
        - mongo:27017
        - --eval
        - " config = {_id:myRS,members:[{_id:0,host:mongo:27017}]}; sleep(3000); rs.initiate(config, { force: true }); "
      resources:
        limits:
          memory: "350Mi"
          cpu: "500m"
        requests:
          memory: "100Mi"
          cpu: "100m"
  restartPolicy: Never
status: {}
