apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\johnm\Documents\repos\machine\docker\development\kompose.exe convert -c --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\johnm\Documents\repos\machine\docker\development\kompose.exe convert -c --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: mongo
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - command:
            - /usr/bin/mongod
            - --bind_ip
            - 0.0.0.0
          image: mongo:4.2-bionic
          imagePullPolicy: "Always"
          name: mongo
          ports:
            - containerPort: 27017
          resources:
            limits:
              memory: "350Mi"
              cpu: "500m"
            requests:
              memory: "100Mi"
              cpu: "100m"
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
      hostname: mongo
      restartPolicy: Always
      {{- if .Values.localVolume }}
      volumes:
        - hostPath:
            path: /data/mongodb #this is mounted in the minikube persistent storage of /data: https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/
          name: mongo-data
      {{- else}}
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: 	machine-mongo-claim
      {{- end}}
status: {}
