{{- define "secrets.clearml" }}
            - name: ClearML__ApiServer
              value: https://api.sil.hosted.allegro.ai
            - name: ClearML__Queue
              value: langtech_20gb
            - name: ClearML__AccessKey
              valueFrom:
                secretKeyRef:
                  name: aqua-ml-data
                  key: ClearML_AccessKey
            - name: ClearML__SecretKey
              valueFrom:
                secretKeyRef:
                  name: aqua-ml-data
                  key: ClearML_SecretKey
{{- end }}
{{- define "secrets.s3" }}
            - name: SharedFile__Uri
              value: s3://aqua-ml-data/
            - name: SharedFile__S3AccessKeyId
              valueFrom:
                secretKeyRef:
                  name: aqua-ml-data
                  key: AWS_ACCESS_KEY_ID
            - name: SharedFile__S3SecretAccessKey
              valueFrom:
                secretKeyRef:
                  name: aqua-ml-data
                  key: AWS_SECRET_ACCESS_KEY
{{- end }}