apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: serval-api
  name: serval-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serval-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: serval-api
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - command:
            - dotnet
            - /app/api_server/Serval.ApiServer.dll
          workingDir: /app/api_server
          env:
            - name: ASPNETCORE_Kestrel__Endpoints__Http__Url
              value: http://*:80
            - name: ASPNETCORE_Kestrel__Endpoints__Http2__Url
              value: http://*:81
            - name: ASPNETCORE_Kestrel__Endpoints__Http2__Protocols
              value: Http2
            - name: ASPNETCORE_ConnectionStrings__Hangfire
              value: mongodb://mongo:27017/serval_jobs
            - name: ASPNETCORE_ConnectionStrings__Mongo
              value: mongodb://mongo:27017/serval
            - name: ASPNETCORE_Logging__LogLevel__Default
              value: Information
            - name: ASPNETCORE_Logging__LogLevel__Microsoft.AspNetCore
              value: Warning
            - name: ASPNETCORE_Translation__Engines__0__Type
              value: Echo
            - name: ASPNETCORE_Translation__Engines__0__Address
              value: http://echo
            - name: ASPNETCORE_Translation__Engines__1__Type
              value: SmtTransfer
            - name: ASPNETCORE_Translation__Engines__1__Address
              value: http://machine-server
              {{- if not .Values.localVolume}}
              {{- template "secrets.clearml" }}
              {{- template "secrets.s3" }}
              {{- end}}
          image: {{ .Values.servalImage}}
          imagePullPolicy: "Always"
          name: serval-api
          ports:
            - containerPort: 80
            - containerPort: 81
          resources:
            limits:
              memory: "1000Mi"
              cpu: "500m"
            requests:
              memory: "100Mi"
              cpu: "100m"
          volumeMounts:
            - mountPath: /var/lib/serval
              name: serval-mount
            - mountPath: /root/.aspnet/DataProtection-Keys
              name: server-keys
      hostname: machine-api-server
      restartPolicy: Always
      {{- if .Values.localVolume }}
      volumes:
        - hostPath:
            path: /host/serval
          name: serval-mount
        - hostPath:
            path: /host/DataProtection-Keys
          name: server-keys
      {{- else}}
      volumes:
        - name: serval-mount
          persistentVolumeClaim:
            claimName: serval-claim
        - name: server-keys
          persistentVolumeClaim:
            claimName: keys-claim
      {{- end}}
status: {}
