apiVersion: v1
kind: Service
metadata:
  labels:
    app: serval-api
  name: serval-api
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app: serval-api
status:
  loadBalancer: {}
