apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - command: ["/bin/sh", "-c"]
          args: ['mongod --replSet myRS --bind_ip 0.0.0.0 & sleep 15s; mongosh --host localhost:27017 --eval '' config = { "_id" : "myRS", "members" : [{"_id" : 0,"host" : "mongo:27017"}] }; rs.initiate(config, { force: true }); '' ; sleep infinity']
          image: mongo:6.0
          imagePullPolicy: "Always"
          name: mongo
          ports:
            - containerPort: 27017
          resources:
            limits:
              memory: "2000Mi"
              cpu: "1000m"
            requests:
              memory: "2000Mi"
              cpu: "1000m"
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
      hostname: mongo
      restartPolicy: Always
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: 	serval-mongo-claim
status: {}
