global using System.Text;
global using System.Text.Json;
global using System.Xml.Linq;
global using Microsoft.Extensions.Options;
global using NSubstitute;
global using NUnit.Framework;
global using Serval.Shared.Configuration;
global using SIL.Machine.Corpora;
global using SIL.Scripture;
