global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Hosting.Internal;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using NSubstitute;
global using NUnit.Framework;
global using RichardSzalay.MockHttp;
global using Serval.Machine.Shared.Configuration;
global using SIL.Machine.Utils;
