apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: serval-claim
  namespace: {{ .Values.namespace}}
spec:
  storageClassName: "longhorn"
  accessModes:
      - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: machine-claim
  namespace: {{ .Values.namespace}}
spec:
  storageClassName: "longhorn"
  accessModes:
      - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keys-claim
  namespace: {{ .Values.namespace}}
spec:
  storageClassName: "longhorn"
  accessModes:
      - ReadWriteMany
  resources:
    requests:
      storage: 50M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: serval-mongo-claim
  namespace: {{ .Values.namespace}}
spec:
  storageClassName: "longhorn"
  accessModes:
      - ReadWriteMany
  resources:
    requests:
      storage: 10Gi