apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: serval-claim
  namespace: {{ .Values.namespace}}
spec:
  storageClassName: "longhorn"
  accessModes:
      - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.servalClaimSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: machine-claim
  namespace: {{ .Values.namespace}}
spec:
  storageClassName: "longhorn"
  accessModes:
      - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.machineClaimSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keys-claim
  namespace: {{ .Values.namespace}}
spec:
  storageClassName: "longhorn"
  accessModes:
      - ReadWriteMany
  resources:
    requests:
      storage: 55M