name: Test CI for E2E

on:
  push:
    branches:
      - "integration_testing"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      SERVAL_CLIENT_ID: ${{ secrets.SERVAL_CLIENT_ID }}
      SERVAL_CLIENT_SECRET: ${{ secrets.SERVAL_CLIENT_SECRET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ClearML_AccessKey: ${{ secrets.ClearML_AccessKey }}
      ClearML_SecretKey: ${{ secrets.ClearML_SecretKey }}
      SERVAL_HOST_URL: http://localhost
      SERVAL_AUTH_URL: https://sil-appbuilder.auth0.com

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Get Machine
        run: cd .. && git clone https://github.com/sillsdev/machine.git && cd machine && dotnet build && cd ../serval

      - name: Start containers
        run: docker compose up -d

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Restore dependencies
        run: dotnet restore

      - name: Check formatting
        run: dotnet csharpier --check .

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Pre-Test
        run: sudo mkdir -p /var/lib/serval && sudo chmod 777 /var/lib/serval

      - name: Test
        run: dotnet test --no-build --verbosity normal --filter "TestCategory!=slow&TestCategory=E2E" -c Release

      - name: Stop containers
        if: always()
        run: docker compose down
