name: Release Serval.Client package

on:
  push:
    tags:
      - "client_*"

jobs:
  publish:
    name: Publish NuGet package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Pack
        run: dotnet pack src/Serval/src/Serval.Client/Serval.Client.csproj -c Release -o artifacts
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: artifacts/*.nupkg
      - name: Push
        run: dotnet nuget push artifacts/*.nupkg -n -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
